// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     backup-topic-record.avsc
 *     backup-topic-consumer-group-offset.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

func writeArrayBackupTopicRecordHeader(r []BackupTopicRecordHeader, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeBackupTopicRecordHeader(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayBackupTopicRecordHeaderWrapper struct {
	Target *[]BackupTopicRecordHeader
}

func (_ *ArrayBackupTopicRecordHeaderWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *ArrayBackupTopicRecordHeaderWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *ArrayBackupTopicRecordHeaderWrapper) Finalize()        {}
func (_ *ArrayBackupTopicRecordHeaderWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r *ArrayBackupTopicRecordHeaderWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayBackupTopicRecordHeaderWrapper) AppendArray() types.Field {
	var v BackupTopicRecordHeader
	v = NewBackupTopicRecordHeader()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
