// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     backup-topic-record.avsc
 *     backup-topic-consumer-group-offset.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

var _ = fmt.Printf

type BackupTopicRecordHeader struct {
	Key Bytes `json:"Key"`

	Value Bytes `json:"Value"`
}

const BackupTopicRecordHeaderAvroCRC64Fingerprint = "͞F\x04\xba\x06I\xc0"

func NewBackupTopicRecordHeader() BackupTopicRecordHeader {
	r := BackupTopicRecordHeader{}
	return r
}

func DeserializeBackupTopicRecordHeader(r io.Reader) (BackupTopicRecordHeader, error) {
	t := NewBackupTopicRecordHeader()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeBackupTopicRecordHeaderFromSchema(r io.Reader, schema string) (BackupTopicRecordHeader, error) {
	t := NewBackupTopicRecordHeader()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeBackupTopicRecordHeader(r BackupTopicRecordHeader, w io.Writer) error {
	var err error
	err = vm.WriteBytes(r.Key, w)
	if err != nil {
		return err
	}
	err = vm.WriteBytes(r.Value, w)
	if err != nil {
		return err
	}
	return err
}

func (r BackupTopicRecordHeader) Serialize(w io.Writer) error {
	return writeBackupTopicRecordHeader(r, w)
}

func (r BackupTopicRecordHeader) Schema() string {
	return "{\"fields\":[{\"name\":\"Key\",\"type\":\"bytes\"},{\"name\":\"Value\",\"type\":\"bytes\"}],\"name\":\"BackupTopicRecordHeader\",\"type\":\"record\"}"
}

func (r BackupTopicRecordHeader) SchemaName() string {
	return "BackupTopicRecordHeader"
}

func (_ BackupTopicRecordHeader) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) SetInt(v int32)       { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) SetLong(v int64)      { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) SetString(v string)   { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *BackupTopicRecordHeader) Get(i int) types.Field {
	switch i {
	case 0:
		return &BytesWrapper{Target: &r.Key}
	case 1:
		return &BytesWrapper{Target: &r.Value}
	}
	panic("Unknown field index")
}

func (r *BackupTopicRecordHeader) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *BackupTopicRecordHeader) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ BackupTopicRecordHeader) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ BackupTopicRecordHeader) Finalize()                        {}

func (_ BackupTopicRecordHeader) AvroCRC64Fingerprint() []byte {
	return []byte(BackupTopicRecordHeaderAvroCRC64Fingerprint)
}

func (r BackupTopicRecordHeader) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Key"], err = json.Marshal(r.Key)
	if err != nil {
		return nil, err
	}
	output["Value"], err = json.Marshal(r.Value)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *BackupTopicRecordHeader) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Key"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Key); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Key")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Value"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Value); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Value")
	}
	return nil
}
