// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     backup-topic-record.avsc
 *     backup-topic-consumer-group-offset.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

var _ = fmt.Printf

type BackupTopicRecord struct {
	Key Bytes `json:"Key"`

	Value Bytes `json:"Value"`

	Headers []BackupTopicRecordHeader `json:"Headers"`

	Timestamp int64 `json:"Timestamp"`

	BlockTimestamp int64 `json:"BlockTimestamp"`

	Topic string `json:"Topic"`

	Partition int32 `json:"Partition"`

	Offset int64 `json:"Offset"`
}

const BackupTopicRecordAvroCRC64Fingerprint = "\xe9\xd4PP\xdbJ\xf7\x9c"

func NewBackupTopicRecord() BackupTopicRecord {
	r := BackupTopicRecord{}
	r.Headers = make([]BackupTopicRecordHeader, 0)

	return r
}

func DeserializeBackupTopicRecord(r io.Reader) (BackupTopicRecord, error) {
	t := NewBackupTopicRecord()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeBackupTopicRecordFromSchema(r io.Reader, schema string) (BackupTopicRecord, error) {
	t := NewBackupTopicRecord()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeBackupTopicRecord(r BackupTopicRecord, w io.Writer) error {
	var err error
	err = vm.WriteBytes(r.Key, w)
	if err != nil {
		return err
	}
	err = vm.WriteBytes(r.Value, w)
	if err != nil {
		return err
	}
	err = writeArrayBackupTopicRecordHeader(r.Headers, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Timestamp, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.BlockTimestamp, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Topic, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Partition, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Offset, w)
	if err != nil {
		return err
	}
	return err
}

func (r BackupTopicRecord) Serialize(w io.Writer) error {
	return writeBackupTopicRecord(r, w)
}

func (r BackupTopicRecord) Schema() string {
	return "{\"fields\":[{\"name\":\"Key\",\"type\":\"bytes\"},{\"name\":\"Value\",\"type\":\"bytes\"},{\"name\":\"Headers\",\"type\":{\"items\":{\"fields\":[{\"name\":\"Key\",\"type\":\"bytes\"},{\"name\":\"Value\",\"type\":\"bytes\"}],\"name\":\"BackupTopicRecordHeader\",\"type\":\"record\"},\"type\":\"array\"}},{\"name\":\"Timestamp\",\"type\":\"long\"},{\"name\":\"BlockTimestamp\",\"type\":\"long\"},{\"name\":\"Topic\",\"type\":\"string\"},{\"name\":\"Partition\",\"type\":\"int\"},{\"name\":\"Offset\",\"type\":\"long\"}],\"name\":\"BackupTopicRecord\",\"type\":\"record\"}"
}

func (r BackupTopicRecord) SchemaName() string {
	return "BackupTopicRecord"
}

func (_ BackupTopicRecord) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ BackupTopicRecord) SetInt(v int32)       { panic("Unsupported operation") }
func (_ BackupTopicRecord) SetLong(v int64)      { panic("Unsupported operation") }
func (_ BackupTopicRecord) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ BackupTopicRecord) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ BackupTopicRecord) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ BackupTopicRecord) SetString(v string)   { panic("Unsupported operation") }
func (_ BackupTopicRecord) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *BackupTopicRecord) Get(i int) types.Field {
	switch i {
	case 0:
		return &BytesWrapper{Target: &r.Key}
	case 1:
		return &BytesWrapper{Target: &r.Value}
	case 2:
		r.Headers = make([]BackupTopicRecordHeader, 0)

		return &ArrayBackupTopicRecordHeaderWrapper{Target: &r.Headers}
	case 3:
		return &types.Long{Target: &r.Timestamp}
	case 4:
		return &types.Long{Target: &r.BlockTimestamp}
	case 5:
		return &types.String{Target: &r.Topic}
	case 6:
		return &types.Int{Target: &r.Partition}
	case 7:
		return &types.Long{Target: &r.Offset}
	}
	panic("Unknown field index")
}

func (r *BackupTopicRecord) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *BackupTopicRecord) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ BackupTopicRecord) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ BackupTopicRecord) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ BackupTopicRecord) Finalize()                        {}

func (_ BackupTopicRecord) AvroCRC64Fingerprint() []byte {
	return []byte(BackupTopicRecordAvroCRC64Fingerprint)
}

func (r BackupTopicRecord) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Key"], err = json.Marshal(r.Key)
	if err != nil {
		return nil, err
	}
	output["Value"], err = json.Marshal(r.Value)
	if err != nil {
		return nil, err
	}
	output["Headers"], err = json.Marshal(r.Headers)
	if err != nil {
		return nil, err
	}
	output["Timestamp"], err = json.Marshal(r.Timestamp)
	if err != nil {
		return nil, err
	}
	output["BlockTimestamp"], err = json.Marshal(r.BlockTimestamp)
	if err != nil {
		return nil, err
	}
	output["Topic"], err = json.Marshal(r.Topic)
	if err != nil {
		return nil, err
	}
	output["Partition"], err = json.Marshal(r.Partition)
	if err != nil {
		return nil, err
	}
	output["Offset"], err = json.Marshal(r.Offset)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *BackupTopicRecord) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Key"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Key); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Key")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Value"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Value); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Value")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Headers"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Headers); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Headers")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Timestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Timestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Timestamp")
	}
	val = func() json.RawMessage {
		if v, ok := fields["BlockTimestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.BlockTimestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for BlockTimestamp")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Topic"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Topic); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Topic")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Partition"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Partition); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Partition")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Offset"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Offset); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Offset")
	}
	return nil
}
