// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     backup-topic-record.avsc
 *     backup-topic-consumer-group-offset.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

var _ = fmt.Printf

type BackupTopicConsumerGroupOffset struct {
	Topic string `json:"Topic"`

	ConsumerGroup string `json:"ConsumerGroup"`

	Partition int32 `json:"Partition"`

	Offset int64 `json:"Offset"`
}

const BackupTopicConsumerGroupOffsetAvroCRC64Fingerprint = "ɟ\xb19YE\v\x9b"

func NewBackupTopicConsumerGroupOffset() BackupTopicConsumerGroupOffset {
	r := BackupTopicConsumerGroupOffset{}
	return r
}

func DeserializeBackupTopicConsumerGroupOffset(r io.Reader) (BackupTopicConsumerGroupOffset, error) {
	t := NewBackupTopicConsumerGroupOffset()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeBackupTopicConsumerGroupOffsetFromSchema(r io.Reader, schema string) (BackupTopicConsumerGroupOffset, error) {
	t := NewBackupTopicConsumerGroupOffset()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeBackupTopicConsumerGroupOffset(r BackupTopicConsumerGroupOffset, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Topic, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.ConsumerGroup, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Partition, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Offset, w)
	if err != nil {
		return err
	}
	return err
}

func (r BackupTopicConsumerGroupOffset) Serialize(w io.Writer) error {
	return writeBackupTopicConsumerGroupOffset(r, w)
}

func (r BackupTopicConsumerGroupOffset) Schema() string {
	return "{\"fields\":[{\"name\":\"Topic\",\"type\":\"string\"},{\"name\":\"ConsumerGroup\",\"type\":\"string\"},{\"name\":\"Partition\",\"type\":\"int\"},{\"name\":\"Offset\",\"type\":\"long\"}],\"name\":\"BackupTopicConsumerGroupOffset\",\"type\":\"record\"}"
}

func (r BackupTopicConsumerGroupOffset) SchemaName() string {
	return "BackupTopicConsumerGroupOffset"
}

func (_ BackupTopicConsumerGroupOffset) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) SetInt(v int32)       { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) SetLong(v int64)      { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) SetString(v string)   { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *BackupTopicConsumerGroupOffset) Get(i int) types.Field {
	switch i {
	case 0:
		return &types.String{Target: &r.Topic}
	case 1:
		return &types.String{Target: &r.ConsumerGroup}
	case 2:
		return &types.Int{Target: &r.Partition}
	case 3:
		return &types.Long{Target: &r.Offset}
	}
	panic("Unknown field index")
}

func (r *BackupTopicConsumerGroupOffset) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *BackupTopicConsumerGroupOffset) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ BackupTopicConsumerGroupOffset) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ BackupTopicConsumerGroupOffset) AppendArray() types.Field { panic("Unsupported operation") }
func (_ BackupTopicConsumerGroupOffset) Finalize()                {}

func (_ BackupTopicConsumerGroupOffset) AvroCRC64Fingerprint() []byte {
	return []byte(BackupTopicConsumerGroupOffsetAvroCRC64Fingerprint)
}

func (r BackupTopicConsumerGroupOffset) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Topic"], err = json.Marshal(r.Topic)
	if err != nil {
		return nil, err
	}
	output["ConsumerGroup"], err = json.Marshal(r.ConsumerGroup)
	if err != nil {
		return nil, err
	}
	output["Partition"], err = json.Marshal(r.Partition)
	if err != nil {
		return nil, err
	}
	output["Offset"], err = json.Marshal(r.Offset)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *BackupTopicConsumerGroupOffset) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Topic"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Topic); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Topic")
	}
	val = func() json.RawMessage {
		if v, ok := fields["ConsumerGroup"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ConsumerGroup); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for ConsumerGroup")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Partition"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Partition); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Partition")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Offset"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Offset); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Offset")
	}
	return nil
}
