// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     backup-topic-record.avsc
 *     backup-topic-consumer-group-offset.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/container"
	"github.com/actgardner/gogen-avro/v9/vm"
)

func NewBackupTopicConsumerGroupOffsetWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewBackupTopicConsumerGroupOffset()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type BackupTopicConsumerGroupOffsetReader struct {
	r io.Reader
	p *vm.Program
}

func NewBackupTopicConsumerGroupOffsetReader(r io.Reader) (*BackupTopicConsumerGroupOffsetReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewBackupTopicConsumerGroupOffset()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &BackupTopicConsumerGroupOffsetReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r BackupTopicConsumerGroupOffsetReader) Read() (BackupTopicConsumerGroupOffset, error) {
	t := NewBackupTopicConsumerGroupOffset()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
