// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     backup-topic-record.avsc
 *     backup-topic-consumer-group-offset.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

type UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnum int

const (
	UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnumBackupTopicRecordHeader UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnum = 0

	UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnumBackupTopicRecord UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnum = 1
)

type UnionBackupTopicRecordHeaderBackupTopicRecord struct {
	BackupTopicRecordHeader BackupTopicRecordHeader
	BackupTopicRecord       BackupTopicRecord
	UnionType               UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnum
}

func writeUnionBackupTopicRecordHeaderBackupTopicRecord(r UnionBackupTopicRecordHeaderBackupTopicRecord, w io.Writer) error {

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnumBackupTopicRecordHeader:
		return writeBackupTopicRecordHeader(r.BackupTopicRecordHeader, w)
	case UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnumBackupTopicRecord:
		return writeBackupTopicRecord(r.BackupTopicRecord, w)
	}
	return fmt.Errorf("invalid value for UnionBackupTopicRecordHeaderBackupTopicRecord")
}

func NewUnionBackupTopicRecordHeaderBackupTopicRecord() UnionBackupTopicRecordHeaderBackupTopicRecord {
	return UnionBackupTopicRecordHeaderBackupTopicRecord{}
}

func (r UnionBackupTopicRecordHeaderBackupTopicRecord) Serialize(w io.Writer) error {
	return writeUnionBackupTopicRecordHeaderBackupTopicRecord(r, w)
}

func DeserializeUnionBackupTopicRecordHeaderBackupTopicRecord(r io.Reader) (UnionBackupTopicRecordHeaderBackupTopicRecord, error) {
	t := NewUnionBackupTopicRecordHeaderBackupTopicRecord()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionBackupTopicRecordHeaderBackupTopicRecordFromSchema(r io.Reader, schema string) (UnionBackupTopicRecordHeaderBackupTopicRecord, error) {
	t := NewUnionBackupTopicRecordHeaderBackupTopicRecord()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r UnionBackupTopicRecordHeaderBackupTopicRecord) Schema() string {
	return "[{\"fields\":[{\"name\":\"Key\",\"type\":\"bytes\"},{\"name\":\"Value\",\"type\":\"bytes\"}],\"name\":\"BackupTopicRecordHeader\",\"type\":\"record\"},{\"fields\":[{\"name\":\"Key\",\"type\":\"bytes\"},{\"name\":\"Value\",\"type\":\"bytes\"},{\"name\":\"Headers\",\"type\":{\"items\":\"BackupTopicRecordHeader\",\"type\":\"array\"}},{\"name\":\"Timestamp\",\"type\":\"long\"},{\"name\":\"BlockTimestamp\",\"type\":\"long\"},{\"name\":\"Topic\",\"type\":\"string\"},{\"name\":\"Partition\",\"type\":\"int\"},{\"name\":\"Offset\",\"type\":\"long\"}],\"name\":\"BackupTopicRecord\",\"type\":\"record\"}]"
}

func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) SetString(v string) {
	panic("Unsupported operation")
}

func (r *UnionBackupTopicRecordHeaderBackupTopicRecord) SetLong(v int64) {

	r.UnionType = (UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnum)(v)
}

func (r *UnionBackupTopicRecordHeaderBackupTopicRecord) Get(i int) types.Field {

	switch i {
	case 0:
		r.BackupTopicRecordHeader = NewBackupTopicRecordHeader()
		return &types.Record{Target: (&r.BackupTopicRecordHeader)}
	case 1:
		r.BackupTopicRecord = NewBackupTopicRecord()
		return &types.Record{Target: (&r.BackupTopicRecord)}
	}
	panic("Unknown field index")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) NullField(i int) {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ UnionBackupTopicRecordHeaderBackupTopicRecord) Finalize() {}

func (r UnionBackupTopicRecordHeaderBackupTopicRecord) MarshalJSON() ([]byte, error) {

	switch r.UnionType {
	case UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnumBackupTopicRecordHeader:
		return json.Marshal(map[string]interface{}{"BackupTopicRecordHeader": r.BackupTopicRecordHeader})
	case UnionBackupTopicRecordHeaderBackupTopicRecordTypeEnumBackupTopicRecord:
		return json.Marshal(map[string]interface{}{"BackupTopicRecord": r.BackupTopicRecord})
	}
	return nil, fmt.Errorf("invalid value for UnionBackupTopicRecordHeaderBackupTopicRecord")
}

func (r *UnionBackupTopicRecordHeaderBackupTopicRecord) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["BackupTopicRecordHeader"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.BackupTopicRecordHeader)
	}
	if value, ok := fields["BackupTopicRecord"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.BackupTopicRecord)
	}
	return fmt.Errorf("invalid value for UnionBackupTopicRecordHeaderBackupTopicRecord")
}
